name: genss
version: 1.6.3
date: 07/01/2016
description: Generic Schreier-Sims

authors:
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

maintainers:
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">=4.5"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.2"
      url: "http://gap-packages.github.io/io/"
    - name: "orb"
      version: ">= 4.5"
      url: "http://gap-packages.github.io/orb/"

www: http://gap-packages.github.io/genss/
readme: http://gap-packages.github.io/genss/README
packageinfo: http://gap-packages.github.io/genss/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/genss/releases/download/v1.6.3/genss-1.6.3.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/genss/releases/download/v1.6.3/genss-1.6.3.tar.bz2

abstract: The <span class="pkgname">genss</span> package implements the    randomised Schreier-Sims algorithm to compute a stabiliser chain    and a base and strong generating set for arbitrary finite groups.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
