name: genss
version: 1.6.7
date: 2022-07-31
description: |
    Generic Schreier-Sims

authors:
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

maintainers:
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.2"
      url: "https://gap-packages.github.io/io"
    - name: "orb"
      version: ">= 4.5"
      url: "https://gap-packages.github.io/orb"

www: https://gap-packages.github.io/genss
readme: README
packageinfo: https://gap-packages.github.io/genss/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/genss/releases/download/v1.6.7/genss-1.6.7.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/genss/releases/download/v1.6.7/genss-1.6.7.tar.bz2

abstract: |
    The <span class="pkgname">genss</span> package implements the    randomised Schreier-Sims algorithm to compute a stabiliser chain    and a base and strong generating set for arbitrary finite groups.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
