name: genss
version: 1.5
date: 31/05/2012
description: genss - generic Schreier-Sims

authors:
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

maintainers:
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

GAP: ">=4.5"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
    - name: "IO"
      version: ">= 4.2"
    - name: "orb"
      version: ">= 4.5"

www: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/genss.html
readme: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/genss/README.genss
packageinfo: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/genss/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/genss/genss-1.5.tar.gz

abstract: The <span class="pkgname">genss</span> package implements the    randomised Schreier-Sims algorithm to compute a stabiliser chain    and a base and strong generating set for arbitrary finite groups.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
