LoadPackage("genss");
Print("Sp_4(7) natural:\n\n");
g := Sp(4,7);
gg := Group(GeneratorsOfGroup(g));
ti := Runtime();
S := StabilizerChain(gg,rec(TryShortOrbit := 10));
ti2 := Runtime();
if Size(S) <> Size(g) then Error("wrong size"); fi;
ti3 := Runtime();
Print("\n");
S := StabilizerChain(g,rec(TryShortOrbit := 10));
ti4 := Runtime();
Print("\nStabChain:\n");
ViewObj(S);
Print("\n\nTime with random verification: ",ti2-ti,"\n");
Print("Time with known size: ",ti4-ti3,"\n");
